=== andreashauschild/jstateio/src/main/resources/ProcessDefinition-schema.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "id" : {
      "type" : "string"
    },
    "name" : {
      "type" : "string"
    },
    "processors" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "states" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "processors" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    },
    "transitions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "fromStateId" : {
            "type" : "string"
          },
          "toStateId" : {
            "type" : "string"
          }
        }
      }
    }
  }
}

=== andreashauschild/jstateio/jstate-test/src/test/resources/BasicTestProcessDefinition.json
{
  "$schema": "ProcessDefinition-schema.json",
  "id": "id_1",
  "name": "ConvertImagesToMpeg",
  "states": [
    {
      "id": "copyImagesToWorkingDir"
    },
    {
      "id": "createMpegFromImages"
    },
    {
      "id": "uploadMpegToServer"
    },
    {
      "id": "cleanupWorkingDir"
    }
  ],
  "transitions": [
    {
      "fromStateId": "",
      "toStateId": "copyImagesToWorkingDir"
    },
    {
      "fromStateId": "copyImagesToWorkingDir",
      "toStateId": "createMpegFromImages"
    },
    {
      "fromStateId": "createMpegFromImages",
      "toStateId": "uploadMpegToServer"
    }
  ],
  "processors": ["io.jstate.test.BasicFunctionTestProcessor"]
}
