=== andreashauschild/jstateio/examples/quarkus-hibernate-panache/src/test/resources/process-templates/ProcessTemplate-schema.json
{
  "$schema" : "http://json-schema.org/draft-07/schema#",
  "type" : "object",
  "properties" : {
    "description" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "processors" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "clazz" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "properties" : {
            "type" : "object"
          }
        }
      }
    },
    "stateDefinitions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "description" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "processors" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    },
    "transitions" : {
      "type" : "array",
      "items" : {
        "type" : "object",
        "properties" : {
          "fromState" : {
            "type" : "string"
          },
          "toState" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      }
    }
  }
}

=== andreashauschild/jstateio/jstate-core/src/test/java/resources/BasicTestProcessDefinition.json
{
  "$schema": "ProcessTemplate-schema.json",
  "id": "id_1",
  "stateDefinitions": [
    {"name": "copyImagesToWorkingDir"},
    {"name": "createMpegFromImages"},
    {"name": "uploadMpegToServer"},
    {"name": "cleanupWorkingDir"}
  ],
  "transitions": [
    {"fromState": "NEW", "toState": ["copyImagesToWorkingDir"]},
    {"fromState": "copyImagesToWorkingDir", "toState": ["createMpegFromImages"]},
    {"fromState": "createMpegFromImages", "toState": ["uploadMpegToServer"]},
    {"fromState": "uploadMpegToServer", "toState": ["cleanupWorkingDir"]},
    {"fromState": "cleanupWorkingDir", "toState": ["FINAL"]}
  ],
  "processors": [
    {
      "clazz": "io.jstate.test.BasicFunctionTestProcessor",
      "description": "For Testing Purpose",
      "properties": {
        "prop1": "value1",
        "prop2": "value2"
      }
    }
  ]
}
